// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/27/2025, 8:22:43 AM
const configMerger = require("/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/plugins/**/*.{js,ts,mjs}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/composables/**/*.{js,ts,mjs}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/utils/**/*.{js,ts,mjs}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ajeeibraheem/Downloads/yolo-gcp-app/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
